### ISSUE TITLE
Use spring.application.name if no wavefront service is configured

### ISSUE THREAD

**Issue by snicoll** [wavefrontHQ/wavefront-spring-boot#33]
`spring.application.name` is a property that is very often used to specify the identify of a particular app (service), especially in cloud-native architectures. 

Right now we have `ApplicationTags` with application name and service.

@adriancole mentions that [in his original PR](https://github.com/wavefrontHQ/wavefront-spring-boot/commit/8bc0a4e26ace0808da6f1d75cbe610d0e7e516d8#diff-9a391bf967f9272a24845ca71fc3717dR52). I was tempted to actually implement that logic directly in the auto-configuration of `ApplicationTags`.

However, I am confused whether we should use application name or service. Looking at the Wavefront dashboard, it seems like the name aggregates an number of "services". From the perspective, I think `spring.application.name` should be used as the default of `wavefront.application.service`.

**Comment by adriancole** [comment]
ps there's both application and also service to decide on

Here's some (overwhelming) background to this point https://github.com/spring-cloud/spring-cloud-sleuth/issues/324

It isn't worth waiting for people to ask later in other words, rather choose which of application/service (maybe both) to default.

side note: in hindsight sleuth's property "spring.zipkin.service.name" isn't conventional (as it should be sleuth namespace in hindsight as we don't support custom servers anymore). But anyway, this could be a secondary default so that users running zipkin and migrating to WF, or simply those using WF, but zipkin on laptops etc, can smoothly worth between things.

**Comment by snicoll** [comment]
I've asked for feedback on what those mean and here is a summary of it

> Application name=The business application, e.g. "webstore" or "accounting". 
> Service=Component within that application.

From the perspective, I think `wavefront.application.service` should use `spring.application.name` if not set explicitly. I have no opinion on `wavefront.application.name`.

**Comment by panghy** [comment]
also don't have an opinion one way or another, both needs to be set to _something_ (that's reasonable from a spring boot perspective)
